task:
  name: macOS
  osx_instance:
    image: big-sur-base
  header_script:
    - for F in "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers/*.h" ; do echo $F ; cat $F ; done
